### ISSUE TITLE
when can I run on my cb

### ISSUE THREAD

**Issue by hnwy** [bddenhartog/chrome-btsync#2]
good!
but I don't know how build a app for chromebook  ^-^

**Comment by bddenhartog** [comment]
@hnwy I'm actually in the process of re-writing this to accommodate changes made to allowed applications on the Web Store. I've gotten a little sidetracked, but should be able to get a working version out this weekend. 

You can watch or star the project and get updates that way; otherwise, I'll update the README to include the web store link when it is live.

You can always use this version by installing the [Extensions Developer Tool](https://chrome.google.com/webstore/detail/chrome-apps-extensions-de/ohmmkhmmmpcnpikjeljgnaoabkaalbgc) and loading the app locally.
